module.exports = [
  ['back-top', 'BackTop'],
  ['breadcrumb', ['Item']],
  ['button', 'Button', ['Group']],
  ['card', 'Card'],
  ['carousel', ['Item']],
  ['checkbox', ['Group']],
  ['collapse', ['Panel']],
  ['date-picker', 'DatePicker'],
  ['dropdown', ['Item', 'Menu']],
  ['form', 'Form', ['Item']],
  ['grid', ['Row', 'Col|name:Col']],
  ['icon'],
  ['loading-bar|global:$Loading'],
  ['input', 'Input'],
  ['menu', ['Group', 'Item', 'Sub']],
  ['message|global:$Message'],
  ['modal|global:$Modal'],
  ['notice|global:$Notice'],
  ['progress', 'Progress'],
  ['radio', ['Group']],
  ['rate', 'Rate'],
  ['select', 'Select', ['Option|name:Option', 'OptionGroup']],
  ['steps', ['Step']],
  ['table', 'Table'],
  ['tabs', ['Pane']],
  ['timeline', ['Item']],
  ['time-picker', 'TimePicker'],
  ['transfer', 'Transfer']
]
